# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.TextField()),
                ('date', models.DateTimeField(verbose_name='Date Published')),
                ('tags', models.CharField(max_length=500)),
                ('makePrivate', models.BooleanField(default=True)),
            ],
        ),
    ]
