# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 12:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_auto_20160828_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 8, 27, 12, 59, 20, 456951, tzinfo=utc), verbose_name='Date Published'),
        ),
    ]
